/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'

import { useGLTF } from '@react-three/drei'

const Model = (props) => {
	const group = useRef()
	const { nodes, materials } = useGLTF('./planet/Unbenannt.gltf')
	// const { nodes, materials } = useGLTF(
	// 	'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/low-poly-spaceship/model.gltf'
	// )
	console.log(materials)
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				geometry={nodes.Assy_Barra_dentada1.children[0].geometry}
				material={nodes.Assy_Barra_dentada1.children[0].material}
			/>
			<mesh
				geometry={nodes.Assy_Barra_dentada1.children[1].geometry}
				material={nodes.Assy_Barra_dentada1.children[1].material}
			/>
			{/* <mesh geometry={nodes.Assy_Barra_dentada1.children[1].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[2].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[3].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[4].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[5].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[6].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[7].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[8].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[9].geometry} material={nodes.P1_Base1.material} />
			<mesh geometry={nodes.Assy_Barra_dentada1.children[10].geometry} material={nodes.P1_Base1.material} /> */}
			{/* <mesh geometry={nodes.P1_Base1.geometry} material={nodes.P1_Base1.material} /> */}
			{/* <mesh geometry={nodes.P2_Barra1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P3_Soporte_lateral1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P4_Platina_cierre11.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P5_Poste_cierre1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P6_Platina_cierre21.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P7_Anclaje_21.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P8_Soporte_resorte1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P9_Anclaje_11.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P10_Cuña_barra1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P10_Cuña_barra2.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P11_Terminal_barra1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P12_Panel_solar1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P13_Leds1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P17_Panel_frontal1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P18_Soporte_Perilla1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.P20_Perilla_desbloqueo1.geometry} material={materials['']} /> */}
			{/* <mesh geometry={nodes.Cube005.geometry} material={materials.Mat0} />
			<mesh geometry={nodes.Cube005_1.geometry} material={materials.Mat1} />
			<mesh geometry={nodes.Cube005_2.geometry} material={materials.Mat2} />
			<mesh geometry={nodes.Cube005_3.geometry} material={materials.Window_Frame} />
			<mesh geometry={nodes.Cube005_4.geometry} material={materials.Mat4} />
			<mesh geometry={nodes.Cube005_5.geometry} material={materials.Mat3} />
			<mesh geometry={nodes.Cube005_6.geometry} material={materials.Window} /> */}
		</group>
	)
}
useGLTF.preload(
	'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/low-poly-spaceship/model1.gltf'
)
// useGLTF.preload('./planet/model1.gltf')

export default Model
